### ISSUE TITLE
Aliproducts

### ISSUE THREAD

**Issue by xiaoaxing** [misads/AliProducts#1]
你好，请问一下能提供Aliproducts的下载链接么？

**Comment by sky186** [comment]
@misads 
您好作者谢谢您的工程，很有帮助^^
有一个问题想要请教你关于你的数据清理详细过程：
 
1、blog中 训练结束后，再继续训练一个epoch ，得到所有样本损失排序，
不可以直接 使用最后保存的模型， 读取所有训练数据   model.eval() 得到所有的损失吗？（我训练的时候没有中断训练 恢复）

2、 数据清理您还有什么好的办法可以推荐吗？

**Comment by misads** [comment]
@sky186 
1. eval也是可以的

2. 可以参考 https://www.bilibili.com/read/cv4027440

**Comment by misads** [comment]
> 你好，请问一下能提供Aliproducts的下载链接么？

你好，根据比赛的隐私条款，我们是不能提供的，你可以向主办方发邮件询问。
